version: '2'
services:
    torch:
      build:
        context: .
        dockerfile: Docker/Dockerfile-torch
      volumes:
          - ./:/root/fast-neural-style
    hdf5:
      build:
        context: .
        dockerfile: Docker/Dockerfile-hdf5
      volumes:
          - ./:/root/training